In [3]:
def name():
    print("Hallo")

In [4]:
name

<function __main__.name()>

In [5]:
{}

{}

In [6]:
halo()

NameError: name 'halo' is not defined

In [7]:
import math
math.sin(0)

0.0

In [8]:
def myfunction(*number):
    a = 0
    for i in range(0, len(number)):
        a = a + number[i]   
    return a
myfunction(1, 2, 3, 4)

10

In [9]:
def myfunction(*number):
    a = 0
    for i in number:
        a += i   
    return a
myfunction(1, 2, 3, 4)

10

In [ ]:
class Person:

    def __init__(self, name, alter) -> None:
        self.name = name
        self.alter = alter

    def hallo(self, freund):
        print(f'{self.name} says hello to {freund}.')

SyntaxError: invalid syntax (2835303707.py, line 7)

In [11]:
person_bob = Person('Bob', 60)

In [12]:
person_bob.hallo()

Hallo!


In [ ]:
person_bob.hallo('Helena')

In [18]:
class Employee:

    def __init__(self, name, alter, company) -> None:
        self.name = name
        self.alter = alter
        self.company = company

        self.email = f'{name}@{company}.de'



    def hallo(self, freund):
        print(f'{self.name} says hello to {freund}.')

In [19]:
person_bob = Employee('Bob', 60, 'Edeka')

In [20]:
person_bob.email

'Bob@Edeka.de'

In [23]:
import numpy as np

In [24]:
rng = np.random.default_rng()

In [29]:
X = rng.normal(0,1,10)
X

array([-0.02987113, -0.0962127 , -0.70946269,  0.27481605,  0.36763213,
       -0.19363558,  0.7146799 ,  1.84415234,  0.78705185,  0.4448718 ])

In [28]:
Y = rng.normal(0,1,10)

In [33]:
np.concatenate((np.array([1,2]),np.array([2,2])), axis=0)

array([1, 2, 2, 2])

In [34]:
np.concatenate((X,Y))

array([-0.02987113, -0.0962127 , -0.70946269,  0.27481605,  0.36763213,
       -0.19363558,  0.7146799 ,  1.84415234,  0.78705185,  0.4448718 ,
       -0.92817073, -0.12255819, -0.50890588, -0.95711302,  0.70718636,
       -0.39643077, -1.12057657, -1.70721471,  0.30155732, -1.79888042])

In [62]:
### Aufgabe 3.1
def kovarianz(X,Y):
    X = np.array(X)
    Y = np.array(Y)
    cov = np.mean(X*Y) - np.mean(X)*np.mean(Y)

    return cov

In [56]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
kovarianz(X,Y)

np.float64(0.6666666666666661)

In [44]:
np.array(X) - 1

array([0, 1, 2])

In [45]:
np.mean(X)

np.float64(2.0)

In [51]:
np.mean(X * Y)

np.float64(10.666666666666666)

In [50]:
for x, y in zip(X,Y):
    print(x*y)

4
10
18


In [65]:
np.cov(np.array(([1,0,4,5,10],[4,3,5,4,3])), ddof=0)

array([[12.4 , -0.4 ],
       [-0.4 ,  0.56]])

In [63]:
kovarianz([1,0,4,5,10],[4,3,5,4,3])

np.float64(-0.3999999999999986)

In [68]:
np.cov(np.array(([1,0,4,5,10],[4,3,5,4,3])), bias=True)

array([[12.4 , -0.4 ],
       [-0.4 ,  0.56]])

In [69]:
import pandas as pd

In [73]:
daten = pd.DataFrame(([1,0,2,3], [9,2,4,5]))

In [76]:
daten.columns = ['A', 'B', 'C', 'D']

In [77]:
daten

A  B  C  D
0  1  0  2  3
1  9  2  4  5

In [79]:
daten['A'].max()

np.int64(9)

In [82]:
daten.aggregate([np.sum,np.max,np.min], axis=1)

/tmp/ipykernel_3736/2312815566.py:1: FutureWarning: The provided callable <function sum at 0x7b83481536a0> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  daten.aggregate([np.sum,np.max,np.min], axis=1)
/tmp/ipykernel_3736/2312815566.py:1: FutureWarning: The provided callable <function max at 0x7b834816c0e0> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  daten.aggregate([np.sum,np.max,np.min], axis=1)
/tmp/ipykernel_3736/2312815566.py:1: FutureWarning: The provided callable <function min at 0x7b834816c220> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  daten.aggregate([np.sum,np.max,np.min], axis=1)


sum  max  min
0    6    3    0
1   20    9    2