In [1]:
import math
math.sin(0)

0.0

In [4]:
def pass_diese_funktion():
	pass

In [5]:
def mittelwert(probe):
	summe = sum(probe)
	return summe / len(probe)

In [6]:
mittelwert([1,2,3])

2.0

In [8]:
def mittelwert(probe: list) -> float:
	"""
	Rechnet den Mittelwert einer Liste.
	"""
	summe = sum(probe)
	return summe / len(probe)

In [ ]:
mittelwert()

In [9]:
def mannschaft(*args):
    print(args)

In [10]:
mannschaft('Tim', 'Bob')

('Tim', 'Bob')


In [11]:
def mannschaft(*spieler):
    anzahl = len(spieler)
    temp = 'Die Mannschaft hat '
    for s in spieler:
        anzahl -= 1
        if anzahl > 0:
            temp += f'{s}, '
        else:
            temp += f'und {s}'
    temp += '.'
    return temp

In [13]:
mannschaft('Tim', 'Bob', 'Tina', 'Helena')

'Die Mannschaft hat Tim, Bob, Tina, und Helena.'

In [ ]:
def add(a,b):
    return a + b

In [36]:
class Employee:

    def __init__(self, name, alter, company) -> None:
        self.name = name
        self.alter = alter
        self.company = company

        self.email = 'email'



    def hallo(self, freund):
        print(f'{self.name} says hello to {freund}.')

In [37]:
person_bob = Employee('Bob', 60, 'Edeka')

In [38]:
person_bob.email

'email'

In [33]:
type(person_bob)

__main__.Employee

In [34]:
person_bob.hallo('Helena')

Bob says hello to Helena.


In [47]:
class BesserListe(list):
    def summe(self):
        return sum(self)

In [48]:
meine_liste = BesserListe([1,2,3])

In [49]:
type(meine_liste)

__main__.BesserListe

In [50]:
meine_liste.append(4)

In [51]:
meine_liste

[1, 2, 3, 4]

In [52]:
meine_liste.summe()

10

In [53]:
import numpy as np

In [69]:
mein_arr = np.array([33.0,45,6,7,8])

In [70]:
type(mein_arr)

numpy.ndarray

In [71]:
mein_arr.dtype

dtype('float64')

In [72]:
mein_arr.max()

np.float64(45.0)

In [73]:
mein_arr.size

5

In [74]:
mein_arr.ndim

1

In [87]:
mein_arr[:-2]

array([33., 45.,  6.])

In [81]:
zeros = np.zeros((5,5,3))

In [82]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [88]:
rng = np.random.default_rng()

In [91]:
X = rng.normal(0,1,10)

In [96]:
np.concatenate((np.array([1,2]),np.array([2,2])), axis=0)

array([1, 2, 2, 2])

In [98]:
zv = np.array((rng.normal(0,1,10),rng.normal(0,1,10)))

In [99]:
zv

array([[ 0.46878802, -0.28752017, -1.59838224,  1.16814092, -0.72683218,
        -0.52913117,  0.67293892, -0.88379142, -0.41484933,  0.67413184],
       [ 0.93458143, -0.76279028, -2.37311073, -0.70805148,  1.61568784,
         1.43855972,  3.34251126, -0.98410426, -1.93722817,  0.04808436]])

In [100]:
zv.size

20

In [101]:
zv.ndim

2

In [102]:
zv.shape

(2, 10)

In [114]:
zv_1 = zv.reshape((2,5,2))

In [115]:
zv_1.shape

(2, 5, 2)

In [116]:
zv_1

array([[[ 0.46878802, -0.28752017],
        [-1.59838224,  1.16814092],
        [-0.72683218, -0.52913117],
        [ 0.67293892, -0.88379142],
        [-0.41484933,  0.67413184]],

       [[ 0.93458143, -0.76279028],
        [-2.37311073, -0.70805148],
        [ 1.61568784,  1.43855972],
        [ 3.34251126, -0.98410426],
        [-1.93722817,  0.04808436]]])

In [125]:
zv_1.max(axis=0)

array([[ 0.93458143, -0.28752017],
       [-1.59838224,  1.16814092],
       [ 1.61568784,  1.43855972],
       [ 3.34251126, -0.88379142],
       [-0.41484933,  0.67413184]])